package I3.UI;

import I3.Classes.UserInfo;
import I3.DatabaseOperation.CustomerDb;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class CustomerPanel extends javax.swing.JFrame {

    // This method initializes the UI components. If using a GUI builder, regenerate this method.
    private void initComponents() {
        // Add your UI initialization code here or regenerate it using your GUI builder.
        // Example:
        pnl_customerDetails = new javax.swing.JPanel();
        initComponents(); // Ensure this method is defined below or regenerate it using your GUI builder
        table_customer = new javax.swing.JTable();
        tf_name = new javax.swing.JTextField();
        tf_address = new javax.swing.JTextField();
        tf_phone = new javax.swing.JTextField();
        tf_type = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        btn_addCustomer = new javax.swing.JButton();
        btn_editCustomer = new javax.swing.JButton();
        btn_deleteCustomer = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        lbl_customerName = new javax.swing.JLabel();
        lbl_customerAddress = new javax.swing.JLabel();
        lbl_customerPhone = new javax.swing.JLabel();
        lbl_customerType = new javax.swing.JLabel();

        // Set up the layout, add components to the frame, and configure properties.
        // This is typically auto-generated by GUI builders.
    }

    private UserInfo user = new UserInfo();
    private final CustomerDb db = new CustomerDb();
    private ResultSet result = null;

    public CustomerPanel() {
        initComponents();
        this.getContentPane().setBackground(new Color(241, 241, 242));
        setTitle("All About Customers");
        populateWithCustomerData();
    }

    private void populateWithCustomerData() {
        result = db.getAllCustomer();
        table_customer.setModel(DbUtils.resultSetToTableModel(result));
    }

    private void ObjectCreation() {
        user = new UserInfo();
        user.setName(tf_name.getText());
        user.setAddress(tf_address.getText());
        user.setPhoneNo(tf_phone.getText());
        user.setType(tf_type.getText());
        try {
            user.setCustomerId(Integer.parseInt(tf_id.getText()));
        } catch (Exception ex) {
            user.setCustomerId(0);
        }
    }

    private void emptyField() {
        btn_addCustomer.setEnabled(true);
        btn_editCustomer.setEnabled(false);
        btn_deleteCustomer.setEnabled(false);

        user = new UserInfo();

        tf_address.setText("");
        tf_id.setText("");
        tf_name.setText("");
        tf_phone.setText("");
        tf_type.setText("");
        table_customer.clearSelection();
    }

    private void displayToTextField(int row) {
        tf_id.setText(table_customer.getModel().getValueAt(row, 0) + "");
        tf_name.setText((String) table_customer.getModel().getValueAt(row, 1));
        tf_address.setText((String) table_customer.getModel().getValueAt(row, 2));
        tf_phone.setText((String) table_customer.getModel().getValueAt(row, 3));
        tf_type.setText((String) table_customer.getModel().getValueAt(row, 4));
    }

    private void btn_addCustomerActionPerformed(java.awt.event.ActionEvent evt) {
        ObjectCreation();
        db.insertCustomer(user);
        populateWithCustomerData();
        emptyField();
    }

    private void table_customerMouseClicked(java.awt.event.MouseEvent evt) {
        user = new UserInfo();
        int row = table_customer.getSelectedRow();
        displayToTextField(row);
        btn_editCustomer.setEnabled(true);
        btn_deleteCustomer.setEnabled(true);
        btn_addCustomer.setEnabled(false);
    }

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {
        emptyField();
    }

    private void btn_editCustomerActionPerformed(java.awt.event.ActionEvent evt) {
        ObjectCreation();
        db.updateCustomer(user);
        populateWithCustomerData();
        emptyField();
    }

    private void btn_deleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {
        int row = table_customer.getSelectedRow();
        int selectedUserId = (int) table_customer.getModel().getValueAt(row, 0);
        db.deleteCustomer(selectedUserId);
        populateWithCustomerData();
        emptyField();
    }

    private void tf_phoneKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerPanel().setVisible(true);
            }
        });
    }

    private javax.swing.JButton btn_addCustomer;
    private javax.swing.JButton btn_deleteCustomer;
    private javax.swing.JButton btn_editCustomer;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_customerName;
    private javax.swing.JLabel lbl_customerAddress;
    private javax.swing.JLabel lbl_customerPhone;
    private javax.swing.JLabel lbl_customerType;
    private javax.swing.JPanel pnl_customerDetails;
    private javax.swing.JTable table_customer;
    private javax.swing.JTextField tf_address;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_phone;
        private javax.swing.JTextField tf_type;
    }
